name:                mgmths
version:             0.0.1
github:              "thkoch2001/mgmths"
license:             GPL-3
author:              "Thomas Koch"
maintainer:          "thomas@koch.ro"
copyright:           "2019 GOOGLE LLC"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thkoch2001/mgmths#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
    - src
    - src/resources
  dependencies:
  - async
  - monad-extras # used in file resource for delay
  - stm
  - system-fileio
  - system-filepath
  - text

executables:
  mgmths-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mgmths

tests:
  mgmths-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mgmths
